import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

# Load credentials from .env file
load_dotenv()

def send_report(report_path):
    sender = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("EMAIL_PASSWORD")
    recipient = os.getenv("RECIPIENT_EMAIL")

    # Create the email container
    msg = MIMEMultipart()
    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = "Your Automated Sales Report is Ready"

    # Email body text
    body = """Hello,

Please find attached your automated sales report generated by the Report Generator.

This report includes:
- Latest sales data from Excel
- AI-generated executive summary

Regards,
Automated Report System"""

    msg.attach(MIMEText(body, "plain"))

    # Attach the PDF report file
    with open(report_path, "rb") as f:
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(f.read())
        encoders.encode_base64(attachment)
        attachment.add_header(
            "Content-Disposition",
            f"attachment; filename=sales_report.pdf"  
         )
        msg.attach(attachment)

    # Connect to Gmail SMTP and send
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())
        print(f"Report sent to {recipient}")


# ─── Test block ───────────────────────────────────────────
if __name__ == "__main__":
    send_report("output/report.pdf")